# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-16 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysisreport', '0002_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
