# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisreport', '0003_appusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appusers',
        ),
    ]
