# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisreport', '0005_email_valid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_valid',
            new_name='emailverify',
        ),
    ]
