# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisreport', '0006_auto_20170322_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='Reg_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
