# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisreport', '0008_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='username',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
