# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysisreport', '0010_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(default=b'', upload_to=b'media/'),
        ),
    ]
