# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisreport', '0011_auto_20170404_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_data',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(default=None, upload_to=b'media/'),
        ),
    ]
