# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisreport', '0012_auto_20170406_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_data',
            field=models.TextField(default=None),
        ),
    ]
